global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'user-service'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['user-service:8080']

  - job_name: 'budget-service'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['budget-service:8081']

  - job_name: 'transaction-service'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['transaction-service:8082']
